// Generated by Selenium IDE

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.time.Duration;

import static org.junit.jupiter.api.Assertions.assertEquals;


public class ChromeTests {
    private static WebDriver driver;

    @BeforeAll
    public static void setUpSystemProperty() {
        System.setProperty("webdriver.chrome.driver", "C:\\chromedriver\\chromedriver87.exe");
        driver = new ChromeDriver();
    }


    @Test
    public void testingClickingOnMenuAndClickingOnSolutionsAfter() {
        driver.get("https://www.netcare.de/en/home/");
        var menuCSSLocation = ".navbar-toggler > div:nth-child(2)";
        driver.findElement(By.cssSelector(menuCSSLocation)).click();
        WebElement solutionsElement = driver.findElement(By.linkText("Solutions"));
        Actions actions = new Actions(driver);
        actions.moveToElement(solutionsElement).click().perform();
        assertEquals("https://www.netcare.de/en/solutions/", driver.getCurrentUrl());
    }

    @Test
    public void testingSwitchingToGermanPage() {
        driver.get("https://www.netcare.de/en/home/");
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
        driver.findElement(By.linkText("DE")).click();
        assertEquals("https://www.netcare.de/", driver.getCurrentUrl());
    }

    @Test
    public void testingClickingOnProfessionalServicesFromHomePage() {
        driver.get("https://www.netcare.de/en/home/");
        driver.findElement(By.xpath("/html/body/div[1]/section[1]/div[2]/div/div[2]/div[1]/div/a/span[2]")).click();
        assertEquals("https://www.netcare.de/en/solutions/professional-services/", driver.getCurrentUrl());
    }

    @AfterAll
    public static void tearDown() {
        driver.close();
    }
}
