// Generated by Selenium IDE

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;

import static org.junit.jupiter.api.Assertions.assertEquals;


public class FireFoxTests {
    private static WebDriver driver;


    @BeforeAll
    static void setUp() {
        System.setProperty("webdriver.gecko.driver", "C:\\gecko\\geckodriver.exe");
        driver = new FirefoxDriver();
    }


    @Test
    public void testingClickingOnMenuAndClickingOnSolutionsAfter() {
        driver.get("https://www.netcare.de/en/home/");
        driver.findElement(By.cssSelector(".navbar-toggler > div:nth-child(2)")).click();
        WebElement solutionsElement = driver.findElement(By.linkText("Solutions"));
        Actions actions = new Actions(driver);
        actions.moveToElement(solutionsElement).click().perform();
        var wait = new WebDriverWait(driver, Duration.ofSeconds(5));
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("/html/body/div[1]/section[2]/div/div[4]/div[2]/p[3]/a")));
        assertEquals("https://www.netcare.de/en/solutions/", driver.getCurrentUrl());
    }

    @Test
    public void testingSwitchingToGermanPage() {
        driver.get("https://www.netcare.de/en/home/");
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(5));
        driver.findElement(By.linkText("DE")).click();
        assertEquals("https://www.netcare.de/", driver.getCurrentUrl());
    }

    @Test
    public void testingClickingOnProfessionalServicesFromHomePage() {
        driver.get("https://www.netcare.de/en/home/");
        driver.findElement(By.xpath("/html/body/div[1]/section[1]/div[2]/div/div[2]/div[1]/div/a/span[2]")).click();
        assertEquals("https://www.netcare.de/en/solutions/professional-services/", driver.getCurrentUrl());
    }

    @AfterAll
    public static void tearDown() {
        driver.close();
    }
}
